<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1 (Python 3.9.7 on win32)" generated="20210903 23:05:30.868" rpa="false" schemaversion="2">
<suite id="s1" name="Validate Login Page" source="C:\Users\Carlos Carvalho\Desktop\Desafio Accenture\desafio-accenture\tests\mobile\validate_login_page.robot">
<kw name="Go To SKY App Login Page" library="validate_login_page.kw" type="SETUP">
<kw name="Go To App Main Screen" library="validate_login_page.kw">
<kw name="Wait Until Element Is Visible" library="AppiumLibrary">
<arg>id=br.com.sky.selfcare:id/2131427895</arg>
<doc>Waits until element specified with `locator` is visible.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210903 23:05:31.193" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210903 23:05:31.190" endtime="20210903 23:05:31.194"/>
</kw>
<msg timestamp="20210903 23:05:31.194" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210903 23:05:31.197" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20210903 23:05:31.190" endtime="20210903 23:05:31.197"/>
</kw>
<kw name="Click Element" library="AppiumLibrary">
<arg>id=br.com.sky.selfcare:id/2131427895</arg>
<doc>Click element identified by `locator`.</doc>
<status status="NOT RUN" starttime="20210903 23:05:31.197" endtime="20210903 23:05:31.197"/>
</kw>
<status status="FAIL" starttime="20210903 23:05:31.190" endtime="20210903 23:05:31.197"/>
</kw>
<kw name="Press Like On Initial App Screen">
<status status="NOT RUN" starttime="20210903 23:05:31.200" endtime="20210903 23:05:31.200"/>
</kw>
<kw name="Click On Login" library="validate_login_page.kw">
<status status="NOT RUN" starttime="20210903 23:05:31.200" endtime="20210903 23:05:31.200"/>
</kw>
<kw name="Validate The Default Login Page" library="validate_login_page.kw">
<status status="NOT RUN" starttime="20210903 23:05:31.200" endtime="20210903 23:05:31.200"/>
</kw>
<status status="FAIL" starttime="20210903 23:05:31.189" endtime="20210903 23:05:31.200"/>
</kw>
<test id="s1-t1" name="Test The Login Page With Invalid CPF">
<status status="FAIL" starttime="20210903 23:05:31.200" endtime="20210903 23:05:31.201">Parent suite setup failed:
No application is open</status>
</test>
<status status="FAIL" starttime="20210903 23:05:30.869" endtime="20210903 23:05:31.203">Suite setup failed:
No application is open</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Validate Login Page">Validate Login Page</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210903 23:05:31.015" level="ERROR">Error in file 'C:\Users\Carlos Carvalho\Desktop\Desafio Accenture\desafio-accenture\resources\base.robot' on line 2: Initializing library 'Browser' with no arguments failed: Couldn't execute node. Please ensure you have node.js installed and in PATH. See https://nodejs.org/ for instructions. Original error is [WinError 2] O sistema n√£o pode encontrar o arquivo especificado
Traceback (most recent call last):
  File "C:\Users\Carlos Carvalho\AppData\Roaming\Python\Python39\site-packages\Browser\browser.py", line 699, in __init__
    self.playwright = Playwright(
  File "C:\Users\Carlos Carvalho\AppData\Roaming\Python\Python39\site-packages\Browser\playwright.py", line 50, in __init__
    self.ensure_node_dependencies()
  File "C:\Users\Carlos Carvalho\AppData\Roaming\Python\Python39\site-packages\Browser\playwright.py", line 65, in ensure_node_dependencies
    raise RuntimeError(</msg>
<msg timestamp="20210903 23:05:31.194" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
